package tools;

import srt.*;

import com.mathworks.toolbox.javabuilder.*;
import com.mathworks.toolbox.javabuilder.internal.MCRConfiguration;
/**
 * TODO: Insert description here. (generated by zrfan)
 */
public class test {

  /**
   * @param args
   */
  public static void main(String[] args) {
    try {
      Object[] result = null;
      photo_feature a = new photo_feature();
      result = a.face_detection(1, "test.jpg");
      String data[]=result[0].toString().split(" ");
      for(String i : data) 
        System.out.println(i);  
    }
    catch (Exception e) {
      
    }
  }

}
